image_root: /workspace/pavan/multimodal/data/multimodal
ann_root: annotation
coco_gt_root: annotation/coco_gt
train_path: /workspace/pavan/multimodal/data/multimodal/correct_data/b_100k.json
val_path: /workspace/pavan/multimodal/data/multimodal/correct_data/id_unverified.json
test_path: /workspace/pavan/multimodal/data/multimodal/correct_data/ood_unverified.json
dataset: WIDOcodebook


# set pretrained as a file path or an url
# pretrained: 
  # https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large.pth
pretrained: /workspace/pavan/multimodal/BLIP/NIPS/b_100k_large_itc_only/checkpoint_best.pth
#pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_coco.pth'
#pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_retrieval_flickr.pth'


# size of vit model; base or large

# vit: 'base'
# batch_size_train: 64
# batch_size_test: 64
# vit_grad_ckpt: True
# vit_ckpt_layer: 4
# init_lr: 1e-5

vit: large
batch_size_train: 64
batch_size_test: 32
vit_grad_ckpt: false
vit_ckpt_layer: 12
init_lr: 5e-6

image_size: 256
queue_size: 57600
alpha: 0.4
k_test: 128
negative_all_rank: true

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 6

