 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: clip
  model_type: "ViT-L-14-336"
  load_pretrained: True
  load_finetuned: False 

  # image_size: 336
  # vit_precision: "fp32"

  # # finetune blip2 with clip-vit-large
  # use_grad_checkpoint: True
  # pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_vitL.pth"
  # vit_model: clip_L  

datasets:
  coco_retrieval: # name of the dataset builder
    vis_processor:
        train:
          name: "clip_image_train"
          image_size: 336
        eval:
          name: "clip_image_eval"
          image_size: 336
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/flickr30k_train.json
          md5: aa31ac474cf6250ebb81d18348a07ed8
          storage: /workspace/multimodal/data/multimodal/final_splits/flickr30k_train.json
        val:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/flickr30k_val.json
          md5: b273847456ef5580e33713b1f7de52a0
          storage: /workspace/multimodal/data/multimodal/final_splits/flickr30k_val.json
        test:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/flickr30k_test.json
          md5: 3ff34b0ef2db02d01c37399f6a2a6cd1
          storage: /workspace/multimodal/data/multimodal/final_splits/flickr30k_test.json
      images:
          storage: /workspace/multimodal/data/multimodal

run:
  task: retrieval
  # optimizer
  use_adam: True
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-6
  min_lr: 0
  # warmup_lr: 1e-8
  # warmup_steps: 1000
  weight_decay: 0.001
  beta2: 0.98
  max_epoch: 6
  batch_size_train: 64
  batch_size_eval: 64
  # lr_layer_decay: 0.95  # layer-wise learning rate decay for the ViT 
  num_workers: 4
  accum_grad_iters: 1

  seed: 42
  output_dir: "output/CLIP/Retrieval_wikido/finetuned_flickr_clip-L14-336"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]
  valid_splits: ["val"]

  run_name: "finetuned_flickr_clip-L14-336"
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: False
  use_dist_eval_sampler: False
